config/routes.rb
EDC::Application.routes.draw do
  match '/tips' => "tips#index"
  match '/trailer' => "trailers#index"
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  # GET /trailers
  # GET /trailers.json
  def index
    @trailers = Trailer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trailers }
    end
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/new
  # GET /trailers/new.json
  def new
    @trailer = Trailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/1/edit
  def edit
    @trailer = Trailer.find(params[:id])
  end

  # POST /trailers
  # POST /trailers.json
  def create
    @trailer = Trailer.new(params[:trailer])

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render json: @trailer, status: :created, location: @trailer }
      else
        format.html { render action: "new" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trailers/1
  # PUT /trailers/1.json
  def update
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      if @trailer.update_attributes(params[:trailer])
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer = Trailer.find(params[:id])
    @trailer.destroy

    respond_to do |format|
      format.html { redirect_to trailers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= simple_form_for(@trailer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<% content_for :title, "EDC 2013 Official Trailer | EDC Las Vegas" %>
<div id="trailer-container" class="page-container">
    <h2>EDC 2013 Official Trailer</h2>
    <h5>The official trailer for Electric Daisy Carnival 2013 in Las Vegas, NV</h5>
    <div class="video-container">
        <!-- <iframe width="1000" height="563" src="http://www.youtube.com/embed/e-PRse6jsiE" frameborder="0" allowfullscreen allowfullscreen="true"></iframe> -->
        <object class="video">
          <param name="movie" value="http://www.youtube.com/embed/e-PRse6jsiE?version=3&autoplay=1"></param>
          <param name="allowScriptAccess" value="always"></param>
          <param name="allowFullScreen" value="true"></param>
          <param name="autoplay" value="true"></param>
          <embed src="http://www.youtube.com/apiplayer?video_id=e-PRse6jsiE&version=3&autoplay=1"
                 type="application/x-shockwave-flash"
                 allowscriptaccess="always"
                 autoplay="1"
                 width="1000" height="563"></embed>
        </object>
    </div>
</div>

app/views/trailers/new.html.erb
<h1>New trailer</h1>

<%= render 'form' %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>