config/routes.rb
EDC::Application.routes.draw do
  match '/tips' => "tips#index"
  match '/trailer' => "trailers#index"
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tips }
    end
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
    @tip = Tip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/new
  # GET /tips/new.json
  def new
    @tip = Tip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/1/edit
  def edit
    @tip = Tip.find(params[:id])
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(params[:tip])

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render json: @tip, status: :created, location: @tip }
      else
        format.html { render action: "new" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tips/1
  # PUT /tips/1.json
  def update
    @tip = Tip.find(params[:id])

    respond_to do |format|
      if @tip.update_attributes(params[:tip])
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy

    respond_to do |format|
      format.html { redirect_to tips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.erb
<%= simple_form_for(@tip) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<% content_for :title, "EDC Las Vegas Tips & Information | EDC Las Vegas" %>
<div id="tips-container">
    <h2>EDC Las Vegas Tips &amp; Information</h2>
    <h5>Make the most of your Electric Daisy Carnival experience with this list of tips from EDC veterans</h5>
    <div class="tips-list">
        <ul class="tips">
            <h3>Important Stuff</h3>
            <li class="tip featured">
                <h4><span>Bring an open mind, positivity and a huge smile!</span></h4>
                <p>This is absolutely the most important tip of them all!  Leave your preconceptions at home...EDC is NOT a concert.  EDC is a community of open-minded, positive, creative &amp; music-loving people that come together to have a blast.  It may take you awhile to get used to the free spirited nature but you'll undoubtedly miss it once the weekend is over.  Don't leave the the positivity in Vegas...bring it home with you and spread it!</p>
            </li>
            <li class="tip featured">
                <h4><span>Expect the unexpected</span></h4>
                <p>This applies in both directions: expect awesome things you never imagined, but also be prepared for hiccups.  When 100,000+ people get together in <a href="">one giant venue</a>, some things are bound to go wrong.  In 2012, EDC's Saturday night festivities had to be shut down for most of the evening due to extremely high winds (this didn't stop many attendees from sitting around in the stadium and creating their own parties).</p>
            </li>
            <li class="tip featured">
                <h4><span>Shuttle passes are highly recommended</span></h4>
                <p>Shuttle passes are worth their weight in gold.  The shuttles run frequently throughout the night and are the quickest way to get to and from the Las Vegas Speedway.  They even have their own dedicated route from the strip to the Las Vegas Speedway.</p>
                <p>Why not drive?  Parking is not the issue, rather, getting out of the parking lot is the issue.  With 10,000+ cars trying to leave the venue at the same time, gridlock is inevitable.  If you plan to park at the venue, expect to spend between 2 and 4 hours sitting in lines to exit the lot.  Oh, and remember to keep that first rule in mind during this time. :)</p>
            </li>
            <li class="tip">
                <h4><span>Cell phones probably won't have service</span></h4>
                <p>This catches many people off-guard.  With the crazy density of people packing limited cell towers around the speedway, you'll be lucky to get a text to go through, much less upload a photo to instagram. </p>
            </li>
        </ul>
        <ul class="tips">
            <h3>Helpful Stuff</h3>
            <li class="tip">
                <h4><span>You'll probably lose your friends at some point</span></h4>
                <p>Staying together in groups of 3 or more can be very difficult in the huge EDC crowds.</p>
            </li>
            <li class="tip">
                <h4><span>Plan a meetup time &amp; place in advance</span></h4>
                <p>It is very easy to get lost in a crowd at EDC, so planning a meeting point and time is strongly recommended. On top of the place and time, its a good idea to have a specific buffer time for friends that might wander in late (e.g. meet at the daisy at 4am and wait up to 15 minutes for everyone to arrive).</p>
            </li>
            <li class="tip">
                <h4><span>Stay hydrated, enjoy tomorrow</span></h4>
                <p>Buy an insomniac water bottle and remember to fill it often throughout the night.  The more water you drink tonight, the more fun you'll have tomorrow.</p>
            </li>
            <li class="tip">
                <h4><span>Good earplugs are recommended</span></h4>
                <p>Your ego is likely telling you that only dorks wear earplugs to a music festival, but your ego isn't doing you any favors.  A good pair of earplugs will reduce the volume just enough to save your ears from days of ringing, but still let you fully enjoy the experience.  We really love the <a href="http://www.amazon.com/Etymotic-Research-ETY-Plugs-Protection-Earplugs/dp/B0044DEESS/ref=sr_1_1?ie=UTF8&tag=edclasvegas-20">Etymotic ER20 Earplugs (~$10)</a>, as well as the <a href="http://www.amazon.com/Alpine-Hearing-Protection-MusicSafe-Classic/dp/B0032BYCWG/ref=pd_sim_hpc_1&tag=edclasvegas-20">Alpine Hearing MusicSafe Earplugs (~$19)</a>.  Both will reduce the volume without disconnecting you from the music and are ALMOST INVISIBLE WHEN WORN!</p>
            </li>
            <li class="tip">
                <h4><span>Don't hesitate to help another person that needs it</span></h4>
                <p>This should go without saying.  If you see someone that needs help, don't hesitate to help.  Expect the same in return (see next tip).</p>
            </li>
            <li class="tip">
                <h4><span>Don't be afraid to ask for help if you need it</span></h4>
                <p>EDC is all about coming together as a group of like-minded people.  Never hesitate to ask for help if you need it, you'll be amazed how many people will be willing to help you at a moment's notice.</p>
            </li>
            <li class="tip">
                <h4><span></span></h4>
                <p></p>
            </li>
        </ul>
        <ul class="tips">
            <h3>Obvious Stuff</h3>
            <li class="tip">
                <h4><span>Bring a valid, unexpired photo ID</span></h4>
                <p>You won't get into EDC unless you are over 18, have a valid photo ID and a ticket.  For safety reasons, there aren't exceptions to these rules, so plan ahead.</p>
            </li>
            <li class="tip">
                <h4><span>More coming soon</span></h4>
                <p></p>
            </li>
            <!-- <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li>
                        <li class="tip">
                            <h4><span></span></h4>
                            <p></p>
                        </li> -->
        </ul>
    </div>
</div>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>