config/routes.rb
EDC::Application.routes.draw do
  match '/tips' => "tips#index"
  match '/trailer' => "trailers#index"
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_header.html.erb
<a id="heading" href="/" title="Back to Home">
    <h1>EDC <span>Las Vegas</span></h1>
    <h2>An Unofficial Hub for Electric Daisy Carnival</h2>
</a>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <%= link_to "Edc", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EDC Las Vegas" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "EDC Las Vegas | The Unofficial Hub for All Things EDC" %>">
    <link href='//fonts.googleapis.com/css?family=Lato:100|Michroma|Open+Sans:400,300,800,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "global", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-31667215-7', 'edclasvegas.com');
      ga('send', 'pageview');

    </script> 
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
    <div id="background"></div><div id="midground"></div><div id="foreground"></div>
    <div class="wrapper">
        <div id="container">
            <header>
                <%= render 'layouts/navigation' %>
                <%= render 'layouts/messages' %>
                <%= render 'layouts/header' %>
            </header>
            <div id="main" role="main">
                <%= yield %>
            </div>
            
        </div> <!--! end of #container -->
        <footer>
          <div class="disclaimer">This website is in no way associated with Insomniac, Inc., Electric Daisy Carnival or any affiliates or subsidiaries, implied or otherwise. Our mission is to provide information to EDC Las Vegas attendees, before &amp; after the show, in a supportive community-based manner.</div>
        </footer>
    </div>
</body>
</html>